[project]
name = "vs-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "fastmcp>=2.2.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
